language: node_js
node_js:
- "4"
addons:
  apt:
    packages:
    - pylint
install:
- make dawn-install
script:
- pylint ./runtime/testy/runtime.py
- make dawn-test
- make dawn-lint
branches:
  only:
    - master
